/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

public class App {
    public static void fizzbuzz() {
        // Your code goes here!

        StringBuilder solution = new StringBuilder();

        for(int i=1; i<=100; i++){
            if(isDiv(i, 3)==false && isDiv(i, 5)==false && isDiv(i,7)==false){
                solution.append(String.format(i+"\n"));
                continue;
            }
            else{
                if(isDiv(i, 3)==true){
                    solution.append("Fizz");
                    
                }
                if(isDiv(i, 5)==true){
                    solution.append("Buzz");
                    
                }
                if(isDiv(i, 7)==true){
                    solution.append("Bang");
                }
            }
            solution.append("\n");
        }
        System.out.println(solution);
    }

    public static boolean isDiv(int inNumA, int inNumB){
        return inNumA%inNumB==0;
    }

    public static void main(String[] args) {
        fizzbuzz();
    }
}
